export const REQUEST_GET_USERS = 'REQUEST_GET_USERS';
export const SUCCESS_GET_USERS = 'SUCCESS_GET_USERS';
export const FAILURE_GET_USERS = 'FAILURE_GET_USERS';

export const REQUEST_GET_USER = 'REQUEST_GET_USER';
export const SUCCESS_GET_USER = 'SUCCESS_GET_USER';
export const FAILURE_GET_USER = 'FAILURE_GET_USER';

export const REQUEST_GET_USER_REPOS = 'REQUEST_GET_USER_REPOS';
export const SUCCESS_GET_USER_REPOS = 'SUCCESS_GET_USER_REPOS';
export const FAILURE_GET_USER_REPOS = 'FAILURE_GET_USER_REPOS';
